<table>
    <tr>
        <th>Selection</th>
        <td>
            <?php if (count($query->selection) === 0): ?>
                *
            <?php else: ?>
                <?php echo implode(",", $query->selection) ?>
            <?php endif ?>
        </td>
    </tr>
    <?php foreach ($query->conditions as $condition) { ?>
        <tr>
            <th>
                <?php if ($condition[3] === "AND"): ?>
                    where
                <?php else: ?>
                    or
                <?php endif ?>
            </th>
            <td><?php echo $condition[0] ?> <?php echo $condition[1] ?> <?php echo $condition[2] ?></td>
        </tr>
    <?php } ?>
    <?php if ($query->limit !== 0): ?>
        <tr>
            <th>Limit</th>
            <td>
                <?php echo $query->limit ?>
            </td>
        </tr>
    <?php endif ?>
    <?php if ($query->offset !== 0): ?>
        <tr>
            <th>Offset</th>
            <td>
                <?php echo $query->offset ?>
            </td>
        </tr>
    <?php endif ?>
    <?php foreach ($query->orderBy as $orderBy) { ?>
        <tr>
            <th>
                Order by
            </th>
            <td><?php echo $orderBy[0] ?> <?php echo $orderBy[1] ?></td>
        </tr>
    <?php } ?>
</table>