<?php if ($query instanceof \UniMapper\Query\Custom): ?>
    <a href="#" class="nette-toggler" rel="#unimapper-panel-query-<?php echo $queryIndex ?>">
        <strong>custom ►</strong>
    </a>
    <div id="unimapper-panel-query-<?php echo $queryIndex ?>" class="nette-collapsed">
        <table>
            <tr>
                <th>Mapper</th>
                <td><?php echo $query->mapper->getName() ?></td>
            </tr>
            <tr>
                <th>Method</th>
                <td><?php echo $query->method ?></td>
            </tr>
            <tr>
                <th>Query</th>
                <td><?php echo $query->query ?></td>
            </tr>
            <?php if ($query->data): ?>
                <?php include __DIR__ . '/queries/orderBy.phtml' ?>
            <?php endif ?>
        </table>
    </div>
<?php elseif ($query instanceof \UniMapper\Query\FindAll): ?>
    <a href="#" class="nette-toggler" rel="#unimapper-panel-query-<?php echo $queryIndex ?>">
        <strong>findAll ►</strong>
    </a>
    <div id="unimapper-panel-query-<?php echo $queryIndex ?>" class="nette-collapsed">
        <table>
            <?php include __DIR__ . '/queries/selection.phtml' ?>
            <?php include __DIR__ . '/queries/conditions.phtml' ?>
            <?php include __DIR__ . '/queries/limit.phtml' ?>
            <?php include __DIR__ . '/queries/offset.phtml' ?>
            <?php include __DIR__ . '/queries/orderBy.phtml' ?>
        </table>
    </div>
<?php elseif ($query instanceof \UniMapper\Query\FindOne): ?>
    <a href="#" class="nette-toggler" rel="#unimapper-panel-query-<?php echo $queryIndex ?>">
        <strong>findOne ►</strong>
    </a>
    <div id="unimapper-panel-query-<?php echo $queryIndex ?>" class="nette-collapsed">
        <table>
            <tr>
                <th>Primary value</th>
                <td>
                    <?php echo $query->primaryValue ?>
                </td>
            </tr>
        </table>
    </div>
<?php elseif ($query instanceof \UniMapper\Query\Count): ?>
    <a href="#" class="nette-toggler" rel="#unimapper-panel-query-<?php echo $queryIndex ?>">
        <strong>count ►</strong>
    </a>
    <div id="unimapper-panel-query-<?php echo $queryIndex ?>" class="nette-collapsed">
        <table>
            <?php include __DIR__ . '/queries/conditions.phtml' ?>
        </table>
    </div>
<?php elseif ($query instanceof \UniMapper\Query\Delete): ?>
    <a href="#" class="nette-toggler" rel="#unimapper-panel-query-<?php echo $queryIndex ?>">
        <strong>delete ►</strong>
    </a>
    <div id="unimapper-panel-query-<?php echo $queryIndex ?>" class="nette-collapsed">
        <table>
            <?php include __DIR__ . '/queries/conditions.phtml' ?>
        </table>
    </div>
<?php elseif ($query instanceof \UniMapper\Query\Insert): ?>
    <a href="#" class="nette-toggler" rel="#unimapper-panel-query-<?php echo $queryIndex ?>">
        <strong>insert ►</strong>
    </a>
    <div id="unimapper-panel-query-<?php echo $queryIndex ?>" class="nette-collapsed">
        <table>
            <?php include __DIR__ . '/queries/data.phtml' ?>
        </table>
    </div>
<?php elseif ($query instanceof \UniMapper\Query\Update): ?>
    <a href="#" class="nette-toggler" rel="#unimapper-panel-query-<?php echo $queryIndex ?>">
        <strong>update ►</strong>
    </a>
    <div id="unimapper-panel-query-<?php echo $queryIndex ?>" class="nette-collapsed">
        <table>
            <?php include __DIR__ . '/queries/conditions.phtml' ?>
        </table>
    </div>
<?php endif ?>