<?php foreach ($query->conditions as $condition) { ?>
    <tr>
        <th>
            <?php if ($condition[3] === "AND"): ?>
                where
            <?php else: ?>
                or
            <?php endif ?>
        </th>
        <td><?php echo $condition[0] ?> <?php echo $condition[1] ?> <?php echo \Nette\Diagnostics\Helpers::clickableDump($condition[2], true) ?></td>
    </tr>
<?php } ?>