<h1>UniMapper queries</h1>
<div class="nette-inner">
    <table>
        <thead>
            <th>Elapsed time</th>
            <th>Repository</th>
            <th>Query</th>
            <th>Result</th>
        </thead>
        <tbody>
        <?php foreach ($this->repositories as $repository): ?>
            <?php foreach ($repository->getLogger()->getQueries() as $queryIndex => $query): ?>
                <?php if ($query->result !== null): ?>
                <tr>
                    <td><?php echo round($query->elapsed, 3) ?> ms</td>
                    <td><?php echo get_class($repository) ?></td>
                    <td>
                        <?php if ($query instanceof \UniMapper\Query\Custom): ?>
                            <a href="#" class="nette-toggler" rel="#unimapper-panel-query-<?php echo $queryIndex ?>">
                                <strong>custom ►</strong>
                            </a>
                            <div id="unimapper-panel-query-<?php echo $queryIndex ?>" class="nette-collapsed">
                                <?php include __DIR__ . '/queries/custom.phtml' ?>
                            </div>
                        <?php elseif ($query instanceof \UniMapper\Query\FindAll): ?>
                            <a href="#" class="nette-toggler" rel="#unimapper-panel-query-<?php echo $queryIndex ?>">
                                <strong>findAll ►</strong>
                            </a>
                            <div id="unimapper-panel-query-<?php echo $queryIndex ?>" class="nette-collapsed">
                                <?php include __DIR__ . '/queries/findAll.phtml' ?>
                            </div>
                        <?php endif ?>
                    </td>
                    <td>
                        <?php if ($query->result instanceof \UniMapper\EntityCollection): ?>
                            <?php if (count($query->result) === 0): ?>
                                [0] <?php echo $query->result->getEntityClass() ?>
                            <?php else: ?>
                                <a href="#" class="nette-toggler" rel="#unimapper-panel-result-<?php echo $queryIndex ?>">
                                    [<?php echo count($query->result) ?>]
                                    <?php echo $query->result->getEntityClass() ?> ►
                                </a>
                                <div id="unimapper-panel-result-<?php echo $queryIndex ?>" class="nette-collapsed">
                                    <?php foreach ($query->result as $entity) { ?>
                                        <?php echo \Nette\Diagnostics\Helpers::clickableDump($entity->getData(), true) ?>
                                    <?php } ?>
                                </div>
                            <?php endif ?>
                        <?php elseif ($query->result instanceof \UniMapper\Entity): ?>
                            <a href="#" class="nette-toggler" rel="#unimapper-panel-result-<?php echo $queryIndex ?>"><?php echo get_class($query->result) ?> ►</a>
                            <div id="unimapper-panel-result-<?php echo $queryIndex ?>" class="nette-collapsed">
                                <?php echo \Nette\Diagnostics\Helpers::clickableDump($query->result->getData(), true) ?>
                            </div>
                        <?php else: ?>
                            <?php echo \Nette\Diagnostics\Helpers::clickableDump($query->result, true) ?>
                        <?php endif ?>
                    </td>
                </tr>
                <?php endif ?>
            <?php endforeach ?>
        <?php endforeach ?>
        </tbody>
    </table>
</div>