<h1>UniMapper queries</h1>
<div class="nette-inner">
    <table>
        <thead>
            <th>Repository</th>
            <th>Query</th>
            <th>Entity</th>
        </thead>
        <tbody>
        <?php foreach ($this->repositories as $repository): ?>
            <?php foreach ($repository->getLogger()->getQueries() as $query): ?>
            <tr>
                <td><?php echo get_class($repository) ?></td>
                <td>
                    <?php echo \Nette\Diagnostics\Helpers::clickableDump($query) ?>
                </td>
                <td>
                    <?php echo $query->entityReflection->getName() ?>
                    <?php echo \Nette\Diagnostics\Helpers::clickableDump($query->entityReflection) ?>
                </td>
            </tr>
            <?php endforeach ?>
        <?php endforeach ?>
        </tbody>
    </table>
</div>